# Generated by Django 4.2.5 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.TextField(max_length=1000)),
                ('gpt_response', models.TextField(max_length=1000)),
            ],
        ),
    ]
